### ISSUE TITLE
Never goes into the callback

### ISSUE THREAD

**Issue by drupol** [RobertFischer/JQuery-PeriodicalUpdater#12]
Hello Robert,

Since yesterday, it seems that the callback is never called.
I've added a console.log() into it, and I never see it in the log history.
It happened since you commented the 'notmodified' condition on line 129.
I'm using jQuery 1.2.6 and the latest version of your library.

**Comment by RobertFischer** [comment]
Yes, it does enter the callback — http://demo.smokejumperit.com/demo.html

Your server is only ever returning "notmodified".  This is not right.

I have changed the code to treat "notmodified" as a success and not an error, although I'm concerned that's going to cause some more issues, so we'll see if it stays that way...
