### ISSUE TITLE
Feature Req: Add 'timeInterval' to .restart() in the handle

### ISSUE THREAD

**Issue by smartssa** [RobertFischer/JQuery-PeriodicalUpdater#17]
As it is right now calling the .restart() method restarts to the last known timeInterval.

It'd be great if restart could take an optional time and restart using that interval.

This is useful for other actions to trigger a proper reset/restart on the periodicalUpdater handle that is available in the return callback.

**Comment by RobertFischer** [comment]
Sounds totally reasonable. Submit a patch and I'll be happy to take it.

**Comment by jondruse** [comment]
This should be fixed now.
