### ISSUE TITLE
Cancel PeriodicalUpdate

### ISSUE THREAD

**Issue by braposo** [RobertFischer/JQuery-PeriodicalUpdater#2]
Hi,

Is it possible to cancel a specific PeriodicalUpdate cycle? And what about all the active cycles?

Thanks!

**Comment by RobertFischer** [comment]
Not currently.  If you're interested in hiring me to implement that, let me know.  Otherwise, feel free to implement it yourself and submit a pull request.

**Comment by RobertFischer** [comment]
Just implemented this.  The PeriodicalUpdater function now returns a handle that you can call .stop() on in order to stop its processing.
