### ISSUE TITLE
Cannot handle multiple PeriodicalUpdaters

### ISSUE THREAD

**Issue by postmodern** [RobertFischer/JQuery-PeriodicalUpdater#20]
I encountered a problem, where I wanted to use multiple PeriodicalUpdaters to update multiple divs. Unfortunately, all of the divs were receiving the same data, which the last PeriodicalUpdater was receiving.

**Comment by k1mgy** [comment]
Please post an example of how you are implementing this.  

Although I think associating individual DOM elements to the updater may be inefficient, I've done this in testing and do not see the same issue.

**Comment by RobertFischer** [comment]
I've got sites where multiple PeriodicalUpdaters are running at the same time, and retrieve distinct data. Based on the age of this issue, I'm going to close it.
