### ISSUE TITLE
Best way to set the timeout to min-timeout on successful pull?

### ISSUE THREAD

**Issue by kineticac** [RobertFischer/JQuery-PeriodicalUpdater#6]
My code wants to "wakeup" to the min-timeout rather than slowly returning to min-timeout by the multiplier (in this case a divider?) whenever there's a success.  What's the best way to extend this to do so?

**Comment by RobertFischer** [comment]
I've just added a "restart" feature.  Does this do what you're looking for?  Otherwise, can you describe what you're looking for a bit better?

**Comment by RobertFischer** [comment]
Closing this due to lack of response. I'm assuming handle.restart() works.
